### ISSUE TITLE
My Api not connceting

### ISSUE THREAD

**Issue by stunnamaneee** [dypfinance/staking-governance-security-audits#8]
Need someone to fix

**Comment by Nikkas93** [comment]
Eee)

**Comment by flofo420** [comment]
> Need someone to fix

>Foreign emphasize to “fix”

**Comment by Habibie44** [comment]
Butuh seseorang untuk memperbaiki

**Comment by syarulyusoff** [comment]
How

**Comment by hainusii** [comment]
[Uploading DYP_STAKING_GOVERNANCE_AUDIT (1) (1) (1).pdf…]()

**Comment by hainusii** [comment]
> Uploading DYP_STAKING_GOVERNANCE_AUDIT (1) (1) (1).pdf…
